/* RESTORE FILELISTONLY
FROM DISK = 'C:\TORESTORE\MYDATABASE.bak'
GO */

RESTORE DATABASE MYDATABASE
FROM DISK = 'C:\TORESTORE\MYDATABASE.bak'
WITH MOVE 'MYDATABASE' TO 'E:\DATA\MYDATABASE.mdf',
MOVE 'MYDATABASE_log' TO 'L:\Logs\MYDATABASE.ldf'

RESTORE DATABASE MYDATABASE2
FROM DISK = 'C:\TORESTORE\MYDATABASE2.bak'
WITH MOVE 'MYDATABASE2' TO 'E:\DATA\MYDATABASE2.mdf',
MOVE 'MYDATABASE2_log' TO 'L:\Logs\MYDATABASE2.ldf'

